<?xml version="1.0" encoding="UTF-8"?>
<test-data
    xmlns="http://pmd.sourceforge.net/rule-tests"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://pmd.sourceforge.net/rule-tests http://pmd.sourceforge.net/rule-tests_1_0_0.xsd">

    <test-code>
        <description>failure case</description>
        <expected-problems>3</expected-problems>
        <code><![CDATA[
public class Foo {
    void bar() {
        try {
        } catch (NullPointerException e) {
        } catch (Exception e) {
        } catch (RuntimeException e) {
        }
    }
}
        ]]></code>
    </test-code>

    <test-code>
        <description>catching another type, ok</description>
        <expected-problems>0</expected-problems>
        <code><![CDATA[
public class Foo {
    void bar() {
        try {
        } catch (FooException e) {
        }
    }
}
class FooException extends RuntimeException {}
        ]]></code>
    </test-code>
    <test-code>
        <description>catching subclass of NPE, ok</description>
        <expected-problems>0</expected-problems>
        <code><![CDATA[
public class Foo {
    void bar() {
        try {
        } catch (FooException e) {
        }
    }
}
class FooException extends NullPointerException {}
        ]]></code>
    </test-code>

    <test-code>
        <description>throwing it, ok</description>
        <expected-problems>0</expected-problems>
        <code><![CDATA[
public class Foo {
    void bar() {
        throw new NullPointerException();
    }
}
        ]]></code>
    </test-code>

    <test-code>
        <description>failure case with multi-catch</description>
        <expected-problems>2</expected-problems>
        <code><![CDATA[
public class Foo {
    void bar() {
        try {
        } catch (NullPointerException | RuntimeException | FooException e) {
        }
    }
}
class FooException extends Exception {}
        ]]></code>
    </test-code>

    <test-code>
        <description>[java] AvoidCatchingGenericException: Can no longer suppress on the exception itself #4873</description>
        <expected-problems>0</expected-problems>
        <code><![CDATA[
public class Example {
    public void example() {
        try {
            someMethod();
        } catch(@SuppressWarnings("PMD.AvoidCatchingGenericException") Exception e) {
            e.printStackTrace();
        }
    }
}
]]></code>
    </test-code>
</test-data>
